jobs:
  - name: aws-cyi-infrastructure-int
    max_in_flight: 1
    plan:
      - in_parallel:
          - put: meta
            resource: meta-integration
          - get: aws-cyi-infrastructure
            trigger: true
            passed:
              - aws-cyi-infrastructure-qa
          - get: emr-launcher-release
            version: { tag: ((emr-launcher-version.integration)) }
            trigger: true
            passed:
              - aws-cyi-infrastructure-qa
          - get: emr-relauncher-release
            version: { tag: ((emr-relauncher-version.integration)) }
            trigger: true
            passed:
              - aws-cyi-infrastructure-qa
          - get: al2-emr-ami
            trigger: true
            passed:
              - aws-cyi-infrastructure-qa
      - .: (( inject meta.plan.terraform-bootstrap ))
        config:
          params:
            AWS_ACC: ((aws_account.integration))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: integration
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: integration
